import { ZoneDefinition, ZoneId } from '../types/zone';

export const ZONE_DEFINITIONS: Record<ZoneId, ZoneDefinition> = {
  ZONA_2: {
    id: 'ZONA_2',
    name: 'Zona 2',
    code: 'Z2',
    alias: 'Lampung & Bali',
    standardPercent: 5,
    promoSabarPercent: 0, // FREE on Promo Sabar!
    description: 'Standar 5% | Promo Sabar: GRATIS (FREE)',
    coverageArea: 'Lampung, Bali',
    cities: [
      'Lampung',
      'Bandar Lampung',
      'Metro',
      'Bali',
      'Denpasar',
      'Badung',
      'Gianyar',
      'Tabanan',
      'Buleleng',
      'Karangasem',
      'Klungkung',
      'Bangli',
      'Jembrana',
    ],
    color: '#34d399', // emerald-400
    accentBg: 'rgba(52, 211, 153, 0.1)',
  },
  ZONA_3: {
    id: 'ZONA_3',
    name: 'Zona 3',
    code: 'Z3',
    alias: 'Palembang, Sumsel, Medan, Padang, Bengkulu, Makassar, Manado, All Kalimantan',
    standardPercent: 10,
    promoSabarPercent: 5, // 5% on Promo Sabar
    description: 'Standar 10% | Promo Sabar: 5%',
    coverageArea: 'Palembang, Sumatera Selatan (selain Lampung), Medan, Padang, Bengkulu, Makassar, Manado, Seluruh Kalimantan',
    cities: [
      'Palembang',
      'Sumatera Selatan',
      'Sumsel',
      'Lubuklinggau',
      'Prabumulih',
      'Pagar Alam',
      'Banyuasin',
      'Ogan Ilir',
      'OKI',
      'OKU',
      'Muara Enim',
      'Lahat',
      'Medan',
      'Sumatera Utara',
      'Sumut',
      'Binjai',
      'Pematangsiantar',
      'Deli Serdang',
      'Padang',
      'Sumatera Barat',
      'Sumbar',
      'Bukittinggi',
      'Payakumbuh',
      'Bengkulu',
      'Makassar',
      'Sulawesi Selatan',
      'Sulsel',
      'Gowa',
      'Maros',
      'Manado',
      'Sulawesi Utara',
      'Sulut',
      'Bitung',
      'Tomohon',
      'All Kalimantan',
      'Kalimantan',
      'Balikpapan',
      'Samarinda',
      'Banjarmasin',
      'Pontianak',
      'Palangkaraya',
      'Tarakan',
      'Banjarbaru',
      'Bontang',
      'Singkawang',
      'Kalimantan Timur',
      'Kalimantan Barat',
      'Kalimantan Selatan',
      'Kalimantan Tengah',
      'Kalimantan Utara',
    ],
    color: '#fbbf24', // amber-400
    accentBg: 'rgba(251, 191, 36, 0.1)',
  },
  ZONA_4: {
    id: 'ZONA_4',
    name: 'Zona 4',
    code: 'Z4',
    alias: 'Kendari, Gorontalo, Ambon, Lombok',
    standardPercent: 15,
    promoSabarPercent: 10, // 10% on Promo Sabar
    description: 'Standar 15% | Promo Sabar: 10%',
    coverageArea: 'Kendari, Gorontalo, Ambon, Lombok (NTB)',
    cities: [
      'Kendari',
      'Sulawesi Tenggara',
      'Sultra',
      'Bau-Bau',
      'Kolaka',
      'Gorontalo',
      'Bone Bolango',
      'Ambon',
      'Maluku',
      'Tual',
      'Lombok',
      'Mataram',
      'Lombok Barat',
      'Lombok Tengah',
      'Lombok Timur',
      'Lombok Utara',
      'NTB',
    ],
    color: '#f97316', // orange-400
    accentBg: 'rgba(249, 115, 22, 0.1)',
  },
  ZONA_5: {
    id: 'ZONA_5',
    name: 'Zona 5',
    code: 'Z5',
    alias: 'Papua, Aceh',
    standardPercent: 18,
    promoSabarPercent: 13, // 13% on Promo Sabar
    description: 'Standar 18% | Promo Sabar: 13%',
    coverageArea: 'Papua, Aceh',
    cities: [
      'Papua',
      'Jayapura',
      'Merauke',
      'Mimika',
      'Timika',
      'Sorong',
      'Manokwari',
      'Papua Barat',
      'Papua Tengah',
      'Papua Selatan',
      'Papua Pegunungan',
      'Papua Barat Daya',
      'Aceh',
      'Banda Aceh',
      'Lhokseumawe',
      'Langsa',
      'Sabang',
      'Meulaboh',
      'Aceh Besar',
      'Aceh Utara',
      'Aceh Tengah',
    ],
    color: '#f43f5e', // rose-400
    accentBg: 'rgba(244, 63, 94, 0.1)',
  },
  ZONA_1: {
    id: 'ZONA_1',
    name: 'Zona 1 (Area Reguler)',
    code: 'Z1',
    alias: 'Jabodetabek & Kota Utama Jawa',
    standardPercent: 0,
    promoSabarPercent: 0,
    description: 'Wilayah inti / Ring 1 (Bebas Selisih Zona)',
    coverageArea: 'Jabodetabek & Kota Utama Jawa',
    cities: ['Jakarta', 'Bogor', 'Depok', 'Tangerang', 'Bekasi', 'Bandung', 'Semarang', 'Surabaya', 'Yogyakarta', 'Solo'],
    color: '#38bdf8', // sky-400
    accentBg: 'rgba(56, 189, 248, 0.1)',
  },
};

export const ZONE_LIST: ZoneDefinition[] = [
  ZONE_DEFINITIONS.ZONA_2,
  ZONE_DEFINITIONS.ZONA_3,
  ZONE_DEFINITIONS.ZONA_4,
  ZONE_DEFINITIONS.ZONA_5,
];

// Quick transaction amount presets
export const NOMINAL_PRESETS = [
  { label: '+500 rb', value: 500000 },
  { label: '+1 jt', value: 1000000 },
  { label: '+2 jt', value: 2000000 },
  { label: '+5 jt', value: 5000000 },
  { label: '+10 jt', value: 10000000 },
];
